name: ci
on:
  pull_request:
  push:
    branches:
      - master
permissions:
  # Sets permission policy for `GITHUB_TOKEN`
  contents: read
jobs:
  x86_64-linux-release:
    timeout-minutes: 540
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: sh ci/x86_64-linux-release.sh
      - uses: actions/upload-artifact@v4
        name: "Upload Files"
        with:
          name: build-release
          path: build-release
